"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path": "."
"base_url": "https://api.crowdin.com"
"preserve_hierarchy": true
files: [
  {
    "source": "/custom_components/mealie/translations/en.json",
    "translation": "/custom_components/mealie/translations/%locale%.json",
    "languages_mapping": {
            "locale": {
                "de": "de",
                "el": "el",
                "en": "en",
                "es-ES": "es-ES",
                "fr": "fr",
                "it": "it",
                "sk": "sk",
                "sl": "sl"                
            }
        }    
  }
]
