add_shopping_list_item:
  name: Add shopping list item
  description: "Add an item to a shopping list."
  fields:
    shopping_list_id:
      name: Shopping List ID
      description: The shopping list id (can be found in attributes of the todo entity).
      required: true
      selector:
        text:
    item:
      name: Item
      description: The shopping list item to add.
      required: true
      selector:
        text:
