# https://www.home-assistant.io/integrations/default_config/
default_config:

# https://www.home-assistant.io/integrations/logger/
logger:
  default: info
  logs:
    custom_components.mealie: debug

debugpy:
   start: true
   wait: false
   port: 5678
