# https://www.home-assistant.io/integrations/default_config/
default_config:

# https://www.home-assistant.io/integrations/logger/
logger:
  default: info
  logs:
    custom_components.mealie: debug

debugpy:
   start: true
   wait: false
   port: 5678

# mealie:
#   breakfast_start: "07:00"
#   breakfast_end: "11:00"
#   lunch_start: "11:30"
#   lunch_end: "14:00"
#   dinner_start: "16:00"
#   dinner_end: "21:00"
